apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelguard-deployment
  labels:
    app: labelguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labelguard
  template:
    metadata:
      labels:
        app: labelguard
    spec:
      containers:
      - name: labelguard
        image: inseefrlab/onyxia-vscode-python:py3.13.5
        imagePullPolicy: Always
        # Correction de la commande pour exécuter le script
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            git clone -b main https://github.com/mateomorin/LabelGuard.git
            cd LabelGuard
            # Installation des dépendances si nécessaire (uv sync ou uv pip install)
            uv run uvicorn app.api:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_URI } }
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_USERNAME } }
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_PASSWORD } }
          - name: MLFLOW_HTTP_REQUEST_TIMEOUT
            value: "1800"
          - name: EMBEDDING_API_BASE_URL
            valueFrom: { secretKeyRef: { name: llm-lab, key: url } }
          - name: EMBEDDING_API_KEY
            valueFrom: { secretKeyRef: { name: llm-lab, key: api_key } }
        resources:
          limits:
            cpu: "8000m"
            memory: "15Gi"
          requests:
            cpu: "400m"
            memory: "2Gi"

