apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelguard-deployment
  labels:
    app: labelguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labelguard
  template:
    metadata:
      labels:
        app: labelguard
    spec:
      containers:
      - name: labelguard
        image: inseefrlab/onyxia-vscode-python:py3.13.5
        imagePullPolicy: Always
        command: ["/bin/bash"]
        source: |
          set -e
          git clone -b main https://github.com/mateomorin/LabelGuard.git
          cd LabelGuard
          uv run uvicorn app.api:app
        ports:
        - containerPort: 8000
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_URI } }
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_USERNAME } }
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom: { secretKeyRef: { name: labelguard-train, key: MLFLOW_TRACKING_PASSWORD } }
          - name: MLFLOW_HTTP_REQUEST_TIMEOUT
            value: "1800"
        resources:
          limits:
            cpu: "8000m"
            memory: "15Gi"
          requests:
            cpu: "400m"
            memory: "2Gi"