apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: labelguard-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - labelguard.lab.sspcloud.fr
  rules:
  - host: labelguard.lab.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: labelguard-service
            port:
              number: 80